db-channel = "pgrst"
db-channel-enabled = true
db-config = true
db-pool = 10
db-prepared-statements = true
db-tx-end = "commit"

jwt-role-claim-key = ".role"
jwt-secret-is-base64 = false

log-level = "error"
openapi-mode = "follow-privileges"
server-timing-enabled = false