services:
  db:
    extends:
      file: base.yaml
      service: base_service
    build:
      context: ./database
    volumes:
      - ./database/data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}
    healthcheck:
      test: ["CMD", "psql", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 5s
    container_name: db

  db-migrations:
    extends:
      file: base.yaml
      service: base_service
    environment:
      - POSTGRES_HOST=db
    build:
      context: ./db-migrations
    depends_on:
      db: 
        condition: service_healthy
    container_name: db-migrations

networks:
  pantheon:
    name: pantheon