services:
  db:
    extends:
      file: base.yaml
      service: base_service
    build:
      context: ./database
    volumes:
      - ./database/data:/var/lib/postgresql
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - pantheon
    healthcheck:
      test: ["CMD", "psql", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 5s
    container_name: db

  db-migrations:
    extends:
      file: base.yaml
      service: base_service
    build:
      context: ./db-migrations
    networks:
      - pantheon
    depends_on:
      db:
        condition: service_healthy
    container_name: db-migrations

  db-interface:
    extends:
      file: base.yaml
      service: base_service
    build:
      context: ./db-interface
    container_name: db-interface
    depends_on:
      db-migrations:
        condition: service_completed_successfully
    ports:
      - ${PGRST_SERVER_PORT}:${PGRST_SERVER_PORT}
      - ${PGRST_ADMIN_SERVER_PORT}:${PGRST_ADMIN_SERVER_PORT}
    networks:
      - pantheon
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-I",
          "http://localhost:${PGRST_ADMIN_SERVER_PORT}/live",
        ]
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 5s

  frontend:
    extends:
      file: base.yaml
      service: base_service
    build:
      context: ./frontend
    container_name: fe
    depends_on:
      db:
        condition: service_healthy
    ports:
      - ${GRAFANA_PORT}:3000
    networks:
      - pantheon
    volumes:
      - ./frontend/data:/var/lib/grafana

  dagster_user_code:
    build:
      context: ./orchestrator
      dockerfile: ./Dockerfile_user_code
    env_file:
      - path: .env
        required: true
    environment:
      DAGSTER_POSTGRES_USER: ${DB_USER}
      DAGSTER_POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      DAGSTER_POSTGRES_DB: ${POSTGRES_DB}
      DAGSTER_POSTGRES_HOST: ${POSTGRES_HOST}
    container_name: dg_uc
    depends_on:
      db-migrations:
        condition: service_completed_successfully
    ports:
      - ${DAGSTER_UC_PORT}:${DAGSTER_UC_PORT}
    networks:
      - pantheon

  dagster_webserver:
    build:
      context: ./orchestrator
      dockerfile: ./Dockerfile_dagster
    env_file:
      - path: .env
        required: true
    environment:
      DAGSTER_POSTGRES_USER: ${DB_USER}
      DAGSTER_POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      DAGSTER_POSTGRES_DB: ${POSTGRES_DB}
      DAGSTER_POSTGRES_HOST: ${POSTGRES_HOST}
    container_name: dg_ws
    depends_on:
      db-migrations:
        condition: service_completed_successfully
      dagster_user_code:
        condition: service_healthy
    entrypoint:
      - uv
      - run
      - --project
      - /orchestrator
      - dagster-webserver
      - -h
      - "0.0.0.0"
      - -p
      - ${DAGSTER_WS_PORT}
      - -w
      - workspace.yaml
    ports:
      - ${DAGSTER_WS_PORT}:${DAGSTER_WS_PORT}
    networks:
      - pantheon

  # dagster_daemon:
  #   build:
  #     context: ./orchestrator

networks:
  pantheon:
    name: pantheon
