
# vim: set ft=dockerfile :
# reference https://docs.dagster.io/deployment/oss/deployment-options/docker and https://docs.astral.sh/uv/guides/integration/docker/#available-images
FROM python:3.14-slim-trixie

# The installer requires curl (and certificates) to download the release archive
RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates
# Download the latest installer
ADD https://astral.sh/uv/install.sh /uv-installer.sh
# Run the installer then remove it
RUN sh /uv-installer.sh && rm /uv-installer.sh

# Ensure the installed binary is on the `PATH`
ENV PATH="/root/.local/bin/:$PATH"
COPY . /src/orchestrator opt/dagster/orchestrator
WORKDIR opt/dagster/orchestrator
RUN uv sync --locked --group dagster-rpc

HEALTHCHECK --timeout=1s --start-period=3s --interval=3s --retries=20 CMD ["sh", "-c", "uv run dagster api grpc-health-check -p $DAGSTER_UC_PORT"]

# CMD allows this to be overridden from run launchers or executors to execute runs and steps
CMD ["sh", "-c", "uv run dagster code-server start -h 0.0.0.0 -p $DAGSTER_UC_PORT -f definitions.py --location-name orchestrator"]
