# vim: set ft=dockerfile :
# reference https://docs.dagster.io/deployment/oss/deployment-options/docker and https://docs.astral.sh/uv/guides/integration/docker/#available-images
FROM python:3.14-slim-trixie

# The installer requires curl (and certificates) to download the release archive
RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates
# Download the latest installer
ADD https://astral.sh/uv/install.sh /uv-installer.sh
# Run the installer then remove it
RUN sh /uv-installer.sh && rm /uv-installer.sh

# Ensure the installed binary is on the `PATH`
ENV PATH="/root/.local/bin/:$PATH"
COPY . /app
WORKDIR /app
RUN uv sync --locked --group dagster-rpc --group dagster-services

ENV DAGSTER_HOME=/opt/dagster/dagster_home/
RUN mkdir -p $DAGSTER_HOME
COPY ./config/dagster.yaml ./config/workspace.yaml $DAGSTER_HOME
WORKDIR $DAGSTER_HOME
